[package]
name = "huff_codegen"
version = "0.1.0"
edition = "2021"
authors = ["Andreas Bigger"]
readme = "README.md"
repository = "https://github.com/huff-language/huff-rs/"
license = "MIT OR Apache-2.0"
description = """
Code Generation Crate for the Huff-Language
"""
keywords = ["huff", "rust", "ethereum", "assembly", "compiler"]

[dependencies]
serde_json = "1.0.81"
proptest = "1.0.0"
huff_utils = { path = "../huff_utils" }
ethers = "0.6.2"
hex = "0.4.3"
tracing = "0.1.34"
