[package]
name = "huff_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
huff_utils = { path = "../huff_utils" }
huff_lexer = { path = "../huff_lexer" }
proptest = "1.0.0"
