[package]
name = "huffr_lexer"
version = "0.1.0"
edition = "2021"
authors = ["Andreas Bigger"]
readme = "README.md"
repository = "https://github.com/huff-language/huffr/"
description = """
Lexical Analysis Crate for the Huff-Language
"""
keywords = ["huff", "lang", "rust", "ethereum", "assembly", "compiler"]
exclude = [ "huffs" ]

[dependencies]
proptest = "1.0.0"
huffr_utils = { path = "../huff_utils" }