[package]
name = "huff_cli"
version = "0.1.0"
edition = "2021"
authors = ["Andreas Bigger"]
readme = "README.md"
repository = "https://github.com/huff-language/huff-rs/"
description = """
Efficient Huff compiler written in rust.
"""
keywords = ["huff", "lang", "rust", "ethereum", "assembly", "compiler"]
exclude = [ "huffs" ]

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
huff_codegen = { path = "../huff_codegen" }
huff_lexer = { path = "../huff_lexer" }
huff_utils = { path = "../huff_utils" }
huff_parser = { path = "../huff_parser" }
rayon = { version = "1.5.3" }

[[bin]]
name = "huff"
path = "src/main.rs"
doc = false