[package]
name = "huff_cli"
version = "0.1.0"
edition = "2021"
authors = ["Andreas Bigger"]
readme = "README.md"
repository = "https://github.com/huff-language/huff-rs/"
description = """
Efficient Huff compiler written in rust.
"""
keywords = ["huff", "lang", "rust", "ethereum", "assembly", "compiler"]
exclude = [ "huffs" ]

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
huff_core = { path = "../huff_core" }
huff_utils = { path = "../huff_utils" }
tracing = "0.1.34"
ethers = "0.6.2"

[[bin]]
name = "huff"
path = "src/huff.rs"
doc = false