[package]
name = "huff_utils"
version = "0.2.0"
edition = "2021"
authors = ["Andreas Bigger"]
readme = "README.md"
repository = "https://github.com/huff-language/huffr/"
description = """
Lexical Analysis Crate for the Huff-Language
"""
keywords = ["huff", "lang", "rust", "ethereum", "assembly", "compiler"]

[dependencies]
strum = "0.24"
strum_macros = "0.24"
codemap-diagnostic = "0.1.1"
